github:
  description: "Apache InLong - a one-stop, full-scenario integration framework for massive data"
  homepage: https://inlong.apache.org/
  features:
    # Enable issues management
    issues: true
  enabled_merge_buttons:
    # enable squash button:
    squash:  true
    # disable merge button:
    merge:   false
    # disable rebase button:
    rebase:  false
  # add protected branches strategy
  protected_branches:
    master:
      required_status_checks:
        # strict means "Require branches to be up to date before merging"
        strict: true
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 2

# Web site staging services:
staging:
  profile: ~
  whoami: master

publish:
  whoami: asf-site

notifications:
  commits: commits@inlong.apache.org
  issues: commits@inlong.apache.org
  pullrequests_status: commits@inlong.apache.org
  pullrequests_comment: commits@inlong.apache.org
  issues_status: commits@inlong.apache.org
  issues_comment: commits@inlong.apache.org
  jira_options: link label worklog
